In [1]:
import pandas as pd
import numpy as np
import pickle

# start from jordan provided MAF
# or do filter=pass



#df = pd.read_csv("mc3.v0.2.8.PUBLIC.maf",sep="\t",usecols=["Gene","Tumor_Sample_Barcode"],low_memory=True)


df = pickle.load(open("/home/janaya2/Desktop/ATGC_paper/figures/tumor_classification/data/data.pkl", "rb"))[1]

df1 = df.groupby(["Hugo_Symbol","Tumor_Sample_Barcode"]).size().unstack(fill_value=0)




#print(df.head(5))
#df1 = df.groupby(['Tumor_Sample_Barcode',"Gene"]).size().unstack(fill_value=0)
print(df1.head(5))

print(df1.shape)

Tumor_Sample_Barcode  TCGA-02-0003-01A-01D-1490-08  \
Hugo_Symbol                                          
A1BG                                             0   
A1CF                                             0   
A2M                                              0   
A2ML1                                            0   
A3GALT2                                          0   

Tumor_Sample_Barcode  TCGA-02-0033-01A-01D-1490-08  \
Hugo_Symbol                                          
A1BG                                             0   
A1CF                                             0   
A2M                                              0   
A2ML1                                            0   
A3GALT2                                          0   

Tumor_Sample_Barcode  TCGA-02-0047-01A-01D-1490-08  \
Hugo_Symbol                                          
A1BG                                             0   
A1CF                                             0   
A2M                       

In [2]:
import json

jsonFile = json.load(open("cases.2020-02-28.json","r"))

print(jsonFile[0]["submitter_id"]) # how to get sample barcode thing

print(jsonFile[0]["project"]["project_id"]) # how to get tumor type

TCGA-CJ-4885
TCGA-KIRC


In [3]:
tumorList = []

df1 = df1.T
def runJson(submitter_id,tList):
    for i in jsonFile:
        if(submitter_id == i["submitter_id"]):
            tList.append(i["project"]["project_id"])
            return True
    tList.append("ERROR")
    return False
            
    
print(df1.index)


for i in df1.index.values:
    print (i[:12])
    
    res = runJson(i[:12],tumorList)
    if(res == False):
        print(i[:12])
    #print(i[:12])
    


#print(tumorList)
tumorTypes = pd.Series(tumorList).to_frame()
tumorTypes = tumorTypes.set_index(df1.index)
#tumorTypes.name = "Tumor Types"
print(tumorTypes)
df1["Tumor Types"] = tumorTypes
#df1.append(tumorTypes,ignore_index=True)




display(df1)

Index(['TCGA-02-0003-01A-01D-1490-08', 'TCGA-02-0033-01A-01D-1490-08',
       'TCGA-02-0047-01A-01D-1490-08', 'TCGA-02-0055-01A-01D-1490-08',
       'TCGA-02-2466-01A-01W-0837-08', 'TCGA-02-2470-01A-01D-1494-08',
       'TCGA-02-2483-01A-01D-1494-08', 'TCGA-02-2485-01A-01D-1494-08',
       'TCGA-02-2486-01A-01D-1494-08', 'TCGA-04-1331-01A-01W-0486-08',
       ...
       'TCGA-ZP-A9D1-01A-11D-A382-10', 'TCGA-ZP-A9D2-01A-11D-A382-10',
       'TCGA-ZP-A9D4-01A-11D-A36X-10', 'TCGA-ZQ-A9CR-01A-11D-A397-08',
       'TCGA-ZR-A9CJ-01B-11D-A387-09', 'TCGA-ZS-A9CD-01A-11D-A36X-10',
       'TCGA-ZS-A9CE-01A-11D-A36X-10', 'TCGA-ZS-A9CF-01A-11D-A382-10',
       'TCGA-ZS-A9CG-01A-11D-A36X-10', 'TCGA-ZX-AA5X-01A-11D-A42O-09'],
      dtype='object', name='Tumor_Sample_Barcode', length=9454)
TCGA-02-0003
TCGA-02-0033
TCGA-02-0047
TCGA-02-0055
TCGA-02-2466
TCGA-02-2470
TCGA-02-2483
TCGA-02-2485
TCGA-02-2486
TCGA-04-1331
TCGA-04-1335
TCGA-04-1336
TCGA-04-1342
TCGA-04-1343
TCGA-04-1346
TCGA-04-1348
TCGA-0

TCGA-2Z-A9J5
TCGA-2Z-A9J6
TCGA-2Z-A9J7
TCGA-2Z-A9J8
TCGA-2Z-A9JD
TCGA-2Z-A9JE
TCGA-2Z-A9JG
TCGA-2Z-A9JI
TCGA-2Z-A9JJ
TCGA-2Z-A9JK
TCGA-2Z-A9JL
TCGA-2Z-A9JM
TCGA-2Z-A9JN
TCGA-2Z-A9JO
TCGA-2Z-A9JP
TCGA-2Z-A9JQ
TCGA-2Z-A9JR
TCGA-2Z-A9JS
TCGA-2Z-A9JT
TCGA-30-1714
TCGA-30-1718
TCGA-30-1853
TCGA-30-1855
TCGA-30-1856
TCGA-30-1857
TCGA-30-1862
TCGA-30-1891
TCGA-31-1950
TCGA-31-1953
TCGA-31-1959
TCGA-32-1970
TCGA-32-1976
TCGA-32-1977
TCGA-32-1979
TCGA-32-1980
TCGA-32-1982
TCGA-32-1986
TCGA-32-1991
TCGA-32-2491
TCGA-32-2494
TCGA-32-2495
TCGA-32-2615
TCGA-32-2616
TCGA-32-2632
TCGA-32-2634
TCGA-32-2638
TCGA-32-4208
TCGA-32-4209
TCGA-32-4210
TCGA-32-4211
TCGA-32-4213
TCGA-32-4719
TCGA-32-5222
TCGA-33-4532
TCGA-33-4533
TCGA-33-4538
TCGA-33-4547
TCGA-33-4566
TCGA-33-4582
TCGA-33-4583
TCGA-33-4586
TCGA-33-4587
TCGA-33-4589
TCGA-33-6737
TCGA-33-6738
TCGA-33-A4WN
TCGA-33-A5GW
TCGA-33-AAS8
TCGA-33-AASB
TCGA-33-AASD
TCGA-33-AASI
TCGA-33-AASJ
TCGA-33-AASL
TCGA-34-2596
TCGA-34-2600
TCGA-34-2604
TCGA-34-2605

TCGA-75-7025
TCGA-75-7027
TCGA-75-7030
TCGA-75-7031
TCGA-76-4925
TCGA-76-4926
TCGA-76-4927
TCGA-76-4928
TCGA-76-4929
TCGA-76-4931
TCGA-76-4932
TCGA-76-4934
TCGA-76-4935
TCGA-76-6191
TCGA-76-6192
TCGA-76-6193
TCGA-76-6280
TCGA-76-6282
TCGA-76-6283
TCGA-76-6285
TCGA-76-6286
TCGA-76-6656
TCGA-76-6657
TCGA-76-6660
TCGA-76-6661
TCGA-76-6662
TCGA-76-6663
TCGA-76-6664
TCGA-77-6842
TCGA-77-6843
TCGA-77-6844
TCGA-77-6845
TCGA-77-7139
TCGA-77-7140
TCGA-77-7141
TCGA-77-7142
TCGA-77-7335
TCGA-77-7337
TCGA-77-7338
TCGA-77-7463
TCGA-77-7465
TCGA-77-8007
TCGA-77-8008
TCGA-77-8009
TCGA-77-8128
TCGA-77-8130
TCGA-77-8131
TCGA-77-8133
TCGA-77-8136
TCGA-77-8138
TCGA-77-8139
TCGA-77-8140
TCGA-77-8143
TCGA-77-8144
TCGA-77-8145
TCGA-77-8146
TCGA-77-8148
TCGA-77-8150
TCGA-77-8153
TCGA-77-8154
TCGA-77-8156
TCGA-77-A5FZ
TCGA-77-A5G1
TCGA-77-A5G3
TCGA-77-A5G6
TCGA-77-A5G7
TCGA-77-A5G8
TCGA-77-A5GA
TCGA-77-A5GB
TCGA-77-A5GF
TCGA-77-A5GH
TCGA-78-7145
TCGA-78-7146
TCGA-78-7147
TCGA-78-7148
TCGA-78-7149
TCGA-78-7150

TCGA-AB-2904
TCGA-AB-2908
TCGA-AB-2909
TCGA-AB-2910
TCGA-AB-2911
TCGA-AB-2912
TCGA-AB-2913
TCGA-AB-2914
TCGA-AB-2915
TCGA-AB-2916
TCGA-AB-2917
TCGA-AB-2918
TCGA-AB-2919
TCGA-AB-2920
TCGA-AB-2921
TCGA-AB-2922
TCGA-AB-2923
TCGA-AB-2924
TCGA-AB-2925
TCGA-AB-2926
TCGA-AB-2927
TCGA-AB-2928
TCGA-AB-2929
TCGA-AB-2930
TCGA-AB-2931
TCGA-AB-2932
TCGA-AB-2933
TCGA-AB-2934
TCGA-AB-2935
TCGA-AB-2936
TCGA-AB-2937
TCGA-AB-2938
TCGA-AB-2939
TCGA-AB-2940
TCGA-AB-2942
TCGA-AB-2943
TCGA-AB-2945
TCGA-AB-2948
TCGA-AB-2949
TCGA-AB-2950
TCGA-AB-2952
TCGA-AB-2954
TCGA-AB-2955
TCGA-AB-2956
TCGA-AB-2957
TCGA-AB-2959
TCGA-AC-A23C
TCGA-AC-A23E
TCGA-AC-A23H
TCGA-AC-A2B8
TCGA-AC-A2BK
TCGA-AC-A2BM
TCGA-AC-A2FB
TCGA-AC-A2FF
TCGA-AC-A2FG
TCGA-AC-A2FK
TCGA-AC-A2FO
TCGA-AC-A2QH
TCGA-AC-A3HN
TCGA-AC-A3OD
TCGA-AC-A3QP
TCGA-AC-A3QQ
TCGA-AC-A3W5
TCGA-AC-A3YI
TCGA-AC-A3YJ
TCGA-AC-A4ZE
TCGA-AC-A5EH
TCGA-AC-A5EI
TCGA-AC-A5XS
TCGA-AC-A5XU
TCGA-AC-A62V
TCGA-AC-A62X
TCGA-AC-A62Y
TCGA-AC-A6IV
TCGA-AC-A6IW
TCGA-AC-A6IX
TCGA-AC-A6NO

TCGA-BF-A3DM
TCGA-BF-A3DN
TCGA-BF-A5EO
TCGA-BF-A5EP
TCGA-BF-A5EQ
TCGA-BF-A5ER
TCGA-BF-A5ES
TCGA-BF-A9VF
TCGA-BF-AAOU
TCGA-BF-AAOX
TCGA-BF-AAP0
TCGA-BF-AAP1
TCGA-BF-AAP2
TCGA-BF-AAP4
TCGA-BF-AAP6
TCGA-BF-AAP7
TCGA-BF-AAP8
TCGA-BG-A0LW
TCGA-BG-A0LX
TCGA-BG-A0M0
TCGA-BG-A0M2
TCGA-BG-A0M3
TCGA-BG-A0M4
TCGA-BG-A0M6
TCGA-BG-A0M7
TCGA-BG-A0M8
TCGA-BG-A0M9
TCGA-BG-A0MA
TCGA-BG-A0MC
TCGA-BG-A0MG
TCGA-BG-A0MI
TCGA-BG-A0MK
TCGA-BG-A0MO
TCGA-BG-A0MQ
TCGA-BG-A0MS
TCGA-BG-A0MT
TCGA-BG-A0MU
TCGA-BG-A0RY
TCGA-BG-A0VT
TCGA-BG-A0VV
TCGA-BG-A0VW
TCGA-BG-A0VX
TCGA-BG-A0VZ
TCGA-BG-A0W1
TCGA-BG-A0W2
TCGA-BG-A0YU
TCGA-BG-A0YV
TCGA-BG-A186
TCGA-BG-A187
TCGA-BG-A18A
TCGA-BG-A18B
TCGA-BG-A18C
TCGA-BG-A220
TCGA-BG-A221
TCGA-BG-A222
TCGA-BG-A2AE
TCGA-BG-A2L7
TCGA-BG-A3EW
TCGA-BG-A3PP
TCGA-BH-A0AU
TCGA-BH-A0AV
TCGA-BH-A0AW
TCGA-BH-A0AY
TCGA-BH-A0AZ
TCGA-BH-A0B0
TCGA-BH-A0B1
TCGA-BH-A0B3
TCGA-BH-A0B4
TCGA-BH-A0B5
TCGA-BH-A0B6
TCGA-BH-A0B7
TCGA-BH-A0B8
TCGA-BH-A0B9
TCGA-BH-A0BA
TCGA-BH-A0BC
TCGA-BH-A0BD
TCGA-BH-A0BF

TCGA-CH-5792
TCGA-CH-5794
TCGA-CI-6619
TCGA-CI-6620
TCGA-CI-6621
TCGA-CI-6622
TCGA-CI-6623
TCGA-CI-6624
TCGA-CJ-4634
TCGA-CJ-4636
TCGA-CJ-4637
TCGA-CJ-4638
TCGA-CJ-4639
TCGA-CJ-4640
TCGA-CJ-4641
TCGA-CJ-4643
TCGA-CJ-4644
TCGA-CJ-4869
TCGA-CJ-4882
TCGA-CJ-4899
TCGA-CJ-4900
TCGA-CJ-4901
TCGA-CJ-4902
TCGA-CJ-4903
TCGA-CJ-4904
TCGA-CJ-4905
TCGA-CJ-4907
TCGA-CJ-4908
TCGA-CJ-4912
TCGA-CJ-4913
TCGA-CJ-4916
TCGA-CJ-4918
TCGA-CJ-4920
TCGA-CJ-4923
TCGA-CJ-5671
TCGA-CJ-5672
TCGA-CJ-5675
TCGA-CJ-5676
TCGA-CJ-5677
TCGA-CJ-5678
TCGA-CJ-5679
TCGA-CJ-5680
TCGA-CJ-5681
TCGA-CJ-5682
TCGA-CJ-5683
TCGA-CJ-5684
TCGA-CJ-5686
TCGA-CJ-5689
TCGA-CJ-6027
TCGA-CJ-6028
TCGA-CJ-6030
TCGA-CJ-6031
TCGA-CJ-6032
TCGA-CJ-6033
TCGA-CK-4947
TCGA-CK-4948
TCGA-CK-4950
TCGA-CK-4951
TCGA-CK-4952
TCGA-CK-5912
TCGA-CK-5913
TCGA-CK-5914
TCGA-CK-5915
TCGA-CK-5916
TCGA-CK-6746
TCGA-CK-6747
TCGA-CK-6748
TCGA-CK-6751
TCGA-CL-4957
TCGA-CL-5917
TCGA-CL-5918
TCGA-CM-4743
TCGA-CM-4744
TCGA-CM-4746
TCGA-CM-4747
TCGA-CM-4748
TCGA-CM-4750

TCGA-DC-6155
TCGA-DC-6157
TCGA-DC-6158
TCGA-DC-6160
TCGA-DC-6681
TCGA-DC-6682
TCGA-DC-6683
TCGA-DD-A113
TCGA-DD-A114
TCGA-DD-A115
TCGA-DD-A116
TCGA-DD-A118
TCGA-DD-A119
TCGA-DD-A11A
TCGA-DD-A11B
TCGA-DD-A11C
TCGA-DD-A11D
TCGA-DD-A1E9
TCGA-DD-A1EB
TCGA-DD-A1EC
TCGA-DD-A1ED
TCGA-DD-A1EE
TCGA-DD-A1EF
TCGA-DD-A1EH
TCGA-DD-A1EI
TCGA-DD-A1EJ
TCGA-DD-A1EK
TCGA-DD-A1EL
TCGA-DD-A39V
TCGA-DD-A39W
TCGA-DD-A39X
TCGA-DD-A39Z
TCGA-DD-A3A2
TCGA-DD-A3A3
TCGA-DD-A3A4
TCGA-DD-A3A5
TCGA-DD-A3A6
TCGA-DD-A3A7
TCGA-DD-A3A8
TCGA-DD-A3A9
TCGA-DD-A4NA
TCGA-DD-A4NB
TCGA-DD-A4ND
TCGA-DD-A4NE
TCGA-DD-A4NF
TCGA-DD-A4NG
TCGA-DD-A4NH
TCGA-DD-A4NI
TCGA-DD-A4NJ
TCGA-DD-A4NK
TCGA-DD-A4NL
TCGA-DD-A4NN
TCGA-DD-A4NO
TCGA-DD-A4NP
TCGA-DD-A4NQ
TCGA-DD-A4NR
TCGA-DD-A4NS
TCGA-DD-A4NV
TCGA-DD-A73A
TCGA-DD-A73B
TCGA-DD-A73C
TCGA-DD-A73D
TCGA-DD-A73E
TCGA-DD-A73F
TCGA-DD-A73G
TCGA-DD-AA3A
TCGA-DD-AAC8
TCGA-DD-AAC9
TCGA-DD-AACA
TCGA-DD-AACB
TCGA-DD-AACC
TCGA-DD-AACD
TCGA-DD-AACE
TCGA-DD-AACF
TCGA-DD-AACG
TCGA-DD-AACH
TCGA-DD-AACI

TCGA-E9-A54Y
TCGA-E9-A5FK
TCGA-E9-A5FL
TCGA-E9-A5UO
TCGA-E9-A6HE
TCGA-EA-A1QS
TCGA-EA-A1QT
TCGA-EA-A3HQ
TCGA-EA-A3HR
TCGA-EA-A3HS
TCGA-EA-A3HT
TCGA-EA-A3HU
TCGA-EA-A3QD
TCGA-EA-A3QE
TCGA-EA-A3Y4
TCGA-EA-A410
TCGA-EA-A411
TCGA-EA-A439
TCGA-EA-A43B
TCGA-EA-A5FO
TCGA-EA-A5O9
TCGA-EA-A5ZD
TCGA-EA-A5ZE
TCGA-EA-A5ZF
TCGA-EA-A6QX
TCGA-EA-A78R
TCGA-EA-A97N
TCGA-EB-A1NK
TCGA-EB-A24C
TCGA-EB-A24D
TCGA-EB-A299
TCGA-EB-A3HV
TCGA-EB-A3XB
TCGA-EB-A3XC
TCGA-EB-A3XD
TCGA-EB-A3XE
TCGA-EB-A3XF
TCGA-EB-A3Y6
TCGA-EB-A3Y7
TCGA-EB-A41A
TCGA-EB-A41B
TCGA-EB-A42Y
TCGA-EB-A42Z
TCGA-EB-A430
TCGA-EB-A431
TCGA-EB-A44N
TCGA-EB-A44O
TCGA-EB-A44P
TCGA-EB-A44Q
TCGA-EB-A44R
TCGA-EB-A4IQ
TCGA-EB-A4IS
TCGA-EB-A4OY
TCGA-EB-A4OZ
TCGA-EB-A4P0
TCGA-EB-A4XL
TCGA-EB-A51B
TCGA-EB-A550
TCGA-EB-A551
TCGA-EB-A553
TCGA-EB-A57M
TCGA-EB-A5FP
TCGA-EB-A5KH
TCGA-EB-A5SE
TCGA-EB-A5SF
TCGA-EB-A5SG
TCGA-EB-A5SH
TCGA-EB-A5UL
TCGA-EB-A5UM
TCGA-EB-A5UN
TCGA-EB-A5VU
TCGA-EB-A6L9
TCGA-EB-A6QY
TCGA-EB-A6QZ
TCGA-EB-A6R0
TCGA-EB-A82B
TCGA-EB-A82C

TCGA-FP-8211
TCGA-FP-8631
TCGA-FP-A4BE
TCGA-FP-A4BF
TCGA-FP-A8CX
TCGA-FP-A9TM
TCGA-FR-A2OS
TCGA-FR-A3R1
TCGA-FR-A3YN
TCGA-FR-A3YO
TCGA-FR-A44A
TCGA-FR-A69P
TCGA-FR-A726
TCGA-FR-A728
TCGA-FR-A729
TCGA-FR-A7U8
TCGA-FR-A7U9
TCGA-FR-A7UA
TCGA-FR-A8YC
TCGA-FR-A8YD
TCGA-FR-A8YE
TCGA-FS-A1YW
TCGA-FS-A1YX
TCGA-FS-A1YY
TCGA-FS-A1Z0
TCGA-FS-A1Z3
TCGA-FS-A1Z4
TCGA-FS-A1Z7
TCGA-FS-A1ZA
TCGA-FS-A1ZB
TCGA-FS-A1ZC
TCGA-FS-A1ZD
TCGA-FS-A1ZE
TCGA-FS-A1ZF
TCGA-FS-A1ZG
TCGA-FS-A1ZH
TCGA-FS-A1ZJ
TCGA-FS-A1ZK
TCGA-FS-A1ZM
TCGA-FS-A1ZN
TCGA-FS-A1ZP
TCGA-FS-A1ZQ
TCGA-FS-A1ZR
TCGA-FS-A1ZS
TCGA-FS-A1ZT
TCGA-FS-A1ZU
TCGA-FS-A1ZW
TCGA-FS-A1ZY
TCGA-FS-A1ZZ
TCGA-FS-A4F0
TCGA-FS-A4F4
TCGA-FS-A4F5
TCGA-FS-A4F8
TCGA-FS-A4F9
TCGA-FS-A4FB
TCGA-FS-A4FC
TCGA-FS-A4FD
TCGA-FT-A3EE
TCGA-FT-A61P
TCGA-FU-A23K
TCGA-FU-A23L
TCGA-FU-A2QG
TCGA-FU-A3EO
TCGA-FU-A3HY
TCGA-FU-A3HZ
TCGA-FU-A3NI
TCGA-FU-A3TQ
TCGA-FU-A3TX
TCGA-FU-A3WB
TCGA-FU-A3YQ
TCGA-FU-A40J
TCGA-FU-A5XV
TCGA-FU-A770
TCGA-FV-A23B
TCGA-FV-A2QQ
TCGA-FV-A2QR
TCGA-FV-A3I0

TCGA-K4-A4AB
TCGA-K4-A4AC
TCGA-K4-A54R
TCGA-K4-A5RH
TCGA-K4-A5RI
TCGA-K4-A5RJ
TCGA-K4-A6FZ
TCGA-K4-A6MB
TCGA-K4-A83P
TCGA-K4-AAQO
TCGA-K6-A3WQ
TCGA-K7-A5RF
TCGA-K7-A5RG
TCGA-K7-A6G5
TCGA-K7-AAU7
TCGA-KB-A6F5
TCGA-KB-A6F7
TCGA-KB-A93G
TCGA-KB-A93H
TCGA-KB-A93J
TCGA-KC-A4BL
TCGA-KC-A4BN
TCGA-KC-A4BO
TCGA-KC-A4BR
TCGA-KC-A4BV
TCGA-KC-A7F3
TCGA-KC-A7F5
TCGA-KC-A7F6
TCGA-KC-A7FA
TCGA-KC-A7FD
TCGA-KC-A7FE
TCGA-KD-A5QS
TCGA-KD-A5QT
TCGA-KD-A5QU
TCGA-KF-A41W
TCGA-KH-A6WC
TCGA-KJ-A3U4
TCGA-KK-A59V
TCGA-KK-A59X
TCGA-KK-A59Y
TCGA-KK-A59Z
TCGA-KK-A5A1
TCGA-KK-A6DY
TCGA-KK-A6E0
TCGA-KK-A6E1
TCGA-KK-A6E2
TCGA-KK-A6E3
TCGA-KK-A6E4
TCGA-KK-A6E5
TCGA-KK-A6E6
TCGA-KK-A6E7
TCGA-KK-A6E8
TCGA-KK-A7AP
TCGA-KK-A7AQ
TCGA-KK-A7AU
TCGA-KK-A7AV
TCGA-KK-A7AW
TCGA-KK-A7AY
TCGA-KK-A7AZ
TCGA-KK-A7B0
TCGA-KK-A7B1
TCGA-KK-A7B2
TCGA-KK-A7B3
TCGA-KK-A7B4
TCGA-KK-A8I4
TCGA-KK-A8I5
TCGA-KK-A8I6
TCGA-KK-A8I7
TCGA-KK-A8I8
TCGA-KK-A8I9
TCGA-KK-A8IA
TCGA-KK-A8IB
TCGA-KK-A8IC
TCGA-KK-A8ID
TCGA-KK-A8IF
TCGA-KK-A8IG
TCGA-KK-A8IH

TCGA-TQ-A7RN
TCGA-TQ-A7RO
TCGA-TQ-A7RP
TCGA-TQ-A7RQ
TCGA-TQ-A7RR
TCGA-TQ-A7RS
TCGA-TQ-A7RU
TCGA-TQ-A7RV
TCGA-TQ-A7RW
TCGA-TQ-A8XE
TCGA-TT-A6YJ
TCGA-TT-A6YK
TCGA-TT-A6YN
TCGA-TT-A6YO
TCGA-TT-A6YP
TCGA-UB-A7MA
TCGA-UB-A7MB
TCGA-UB-A7MC
TCGA-UB-A7MD
TCGA-UB-A7ME
TCGA-UB-A7MF
TCGA-UB-AA0U
TCGA-UB-AA0V
TCGA-UC-A7PD
TCGA-UC-A7PF
TCGA-UC-A7PG
TCGA-UC-A7PI
TCGA-UE-A6QT
TCGA-UE-A6QU
TCGA-UF-A718
TCGA-UF-A719
TCGA-UF-A71A
TCGA-UF-A71B
TCGA-UF-A71D
TCGA-UF-A71E
TCGA-UF-A7J9
TCGA-UF-A7JA
TCGA-UF-A7JC
TCGA-UF-A7JD
TCGA-UF-A7JF
TCGA-UF-A7JH
TCGA-UF-A7JJ
TCGA-UF-A7JK
TCGA-UF-A7JO
TCGA-UF-A7JS
TCGA-UF-A7JT
TCGA-UF-A7JV
TCGA-UL-AAZ6
TCGA-UN-AAZ9
TCGA-UP-A6WW
TCGA-US-A774
TCGA-US-A776
TCGA-US-A779
TCGA-US-A77E
TCGA-US-A77G
TCGA-UU-A93S
TCGA-UY-A78K
TCGA-UY-A78L
TCGA-UY-A78M
TCGA-UY-A78N
TCGA-UY-A78O
TCGA-UY-A78P
TCGA-UY-A8OB
TCGA-UY-A8OC
TCGA-UY-A8OD
TCGA-UY-A9PA
TCGA-UY-A9PB
TCGA-UY-A9PD
TCGA-UY-A9PE
TCGA-UY-A9PF
TCGA-UY-A9PH
TCGA-UZ-A9PJ
TCGA-UZ-A9PK
TCGA-UZ-A9PL
TCGA-UZ-A9PM
TCGA-UZ-A9PN
TCGA-UZ-A9PO

Hugo_Symbol                   A1BG  A1CF  A2M  A2ML1  A3GALT2  A4GALT  A4GNT  \
Tumor_Sample_Barcode                                                           
TCGA-02-0003-01A-01D-1490-08     0     0    0      0        0       0      0   
TCGA-02-0033-01A-01D-1490-08     0     0    0      0        0       0      0   
TCGA-02-0047-01A-01D-1490-08     0     0    0      0        0       0      0   
TCGA-02-0055-01A-01D-1490-08     0     0    0      0        0       0      0   
TCGA-02-2466-01A-01W-0837-08     0     0    0      0        0       0      0   
...                            ...   ...  ...    ...      ...     ...    ...   
TCGA-ZS-A9CD-01A-11D-A36X-10     0     0    0      0        0       0      0   
TCGA-ZS-A9CE-01A-11D-A36X-10     0     0    0      0        0       0      0   
TCGA-ZS-A9CF-01A-11D-A382-10     0     0    0      0        0       0      0   
TCGA-ZS-A9CG-01A-11D-A36X-10     0     0    0      0        0       0      0   
TCGA-ZX-AA5X-01A-11D-A42O-09     0     0    0      0        0       0      0   

Hugo_Symbol                   AAAS  AACS  AADAC  ...  ZXDC  ZYG11A  ZYG11B  \
Tumor_Sample_Barcode                             ...                         
TCGA-02-0003-01A-01D-1490-08     0     0      0  ...     0       0       0   
TCGA-02-0033-01A-01D-1490-08     0     0      0  ...     0       0       0   
TCGA-02-0047-01A-01D-1490-08     0     0      0  ...     0       0       0   
TCGA-02-0055-01A-01D-1490-08     0     0      0  ...     0       0       0   
TCGA-02-2466-01A-01W-0837-08     0     0      0  ...     0       0       0   
...                            ...   ...    ...  ...   ...     ...     ...   
TCGA-ZS-A9CD-01A-11D-A36X-10     0     0      0  ...     0       0       0   
TCGA-ZS-A9CE-01A-11D-A36X-10     0     0      0  ...     0       0       0   
TCGA-ZS-A9CF-01A-11D-A382-10     0     0      0  ...     0       0       0   
TCGA-ZS-A9CG-01A-11D-A36X-10     0     0      0  ...     0       0       0   
TCGA-ZX-AA5X-01A-11D-A42O-09     0     0      0  ...     0       0       0   

Hugo_Symbol                   ZYX  ZZEF1  ZZZ3  hsa-mir-1199  hsa-mir-150  \
Tumor_Sample_Barcode                                                        
TCGA-02-0003-01A-01D-1490-08    0      0     0             0            0   
TCGA-02-0033-01A-01D-1490-08    0      0     0             0            0   
TCGA-02-0047-01A-01D-1490-08    0      0     0             0            0   
TCGA-02-0055-01A-01D-1490-08    0      0     0             0            0   
TCGA-02-2466-01A-01W-0837-08    0      0     0             0            0   
...                           ...    ...   ...           ...          ...   
TCGA-ZS-A9CD-01A-11D-A36X-10    0      0     0             0            0   
TCGA-ZS-A9CE-01A-11D-A36X-10    0      0     0             0            0   
TCGA-ZS-A9CF-01A-11D-A382-10    0      0     0             0            0   
TCGA-ZS-A9CG-01A-11D-A36X-10    0      0     0             0            0   
TCGA-ZX-AA5X-01A-11D-A42O-09    0      0     0             0            0   

Hugo_Symbol                   snoU13  Tumor Types  
Tumor_Sample_Barcode                               
TCGA-02-0003-01A-01D-1490-08       0     TCGA-GBM  
TCGA-02-0033-01A-01D-1490-08       0     TCGA-GBM  
TCGA-02-0047-01A-01D-1490-08       0     TCGA-GBM  
TCGA-02-0055-01A-01D-1490-08       0     TCGA-GBM  
TCGA-02-2466-01A-01W-0837-08       0     TCGA-GBM  
...                              ...          ...  
TCGA-ZS-A9CD-01A-11D-A36X-10       0    TCGA-LIHC  
TCGA-ZS-A9CE-01A-11D-A36X-10       0    TCGA-LIHC  
TCGA-ZS-A9CF-01A-11D-A382-10       0    TCGA-LIHC  
TCGA-ZS-A9CG-01A-11D-A36X-10       0    TCGA-LIHC  
TCGA-ZX-AA5X-01A-11D-A42O-09       0    TCGA-CESC  

[9454 rows x 19597 columns]

In [4]:
n = df1.to_numpy()
print(n)

counts = {}

for i in n:
    tumorName = i[-1]
    if(tumorName in counts):
        counts[tumorName] = counts[tumorName] + 1
    else:
        counts[tumorName] = 1
        
print(sorted(counts.items(), key=lambda x: x[1]))
sumvar = 0
for key,val in counts.items():
    sumvar = sumvar + counts[key]
    
print(sumvar)

[[0 0 0 ... 0 0 'TCGA-GBM']
 [0 0 0 ... 0 0 'TCGA-GBM']
 [0 0 0 ... 0 0 'TCGA-GBM']
 ...
 [0 0 0 ... 0 0 'TCGA-LIHC']
 [0 0 0 ... 0 0 'TCGA-LIHC']
 [0 0 0 ... 0 0 'TCGA-CESC']]
[('TCGA-TGCT', 128), ('TCGA-READ', 134), ('TCGA-LAML', 137), ('TCGA-PAAD', 177), ('TCGA-PCPG', 179), ('TCGA-ESCA', 184), ('TCGA-SARC', 236), ('TCGA-KIRP', 281), ('TCGA-CESC', 289), ('TCGA-OV', 355), ('TCGA-LIHC', 363), ('TCGA-COAD', 367), ('TCGA-KIRC', 369), ('TCGA-GBM', 389), ('TCGA-BLCA', 411), ('TCGA-STAD', 439), ('TCGA-SKCM', 466), ('TCGA-LUSC', 485), ('TCGA-THCA', 491), ('TCGA-PRAD', 495), ('TCGA-HNSC', 507), ('TCGA-LGG', 509), ('TCGA-LUAD', 515), ('TCGA-UCEC', 528), ('TCGA-BRCA', 1020)]
9454


In [5]:
print(n.shape)
data = n[:,:-1]

data[data>1] = 1

labels = n[:,-1]
print(labels)
print(data)
print(data.shape)

(9454, 19597)
['TCGA-GBM' 'TCGA-GBM' 'TCGA-GBM' ... 'TCGA-LIHC' 'TCGA-LIHC' 'TCGA-CESC']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(9454, 19596)


In [6]:
data = data.T

In [7]:
print(data)
print(data.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(19596, 9454)


In [8]:
data_sum = np.sum(data,axis=1)
print(data_sum.shape)

(19596,)


In [9]:
print(data_sum)

[87 199 318 ... 10 1 30]


In [10]:
indices = np.arange(0,len(data_sum))
print(indices)

[    0     1     2 ... 19593 19594 19595]


In [11]:
data_rows = np.vstack((data_sum,indices))
print(data_rows)

[[87 199 318 ... 10 1 30]
 [0 1 2 ... 19593 19594 19595]]


In [12]:
print(data_rows[0][17445])

3412


In [13]:
data_rows.shape

(2, 19596)

In [14]:
indices1 = data_rows[0].argsort()
data_rows[0] = data_rows[0][indices1[::-1]]
data_rows[1] = data_rows[1][indices1[::-1]]
print(data_rows)

[[3559 3412 2282 ... 1 1 1]
 [17994 17445 10504 ... 6783 4513 7853]]


In [15]:
data_indices_only = np.delete(data_rows,0,0)

print(data_indices_only)

[[17994 17445 10504 ... 6783 4513 7853]]


In [16]:
groups = []
sim_thresh = 0.05
n_thresh = 5
dat = data_indices_only[0]
grouped = set()

for i in range(len(dat)):
    if(i%1000 == 0):
        print(i)
    if(dat[i] not in grouped):
        grouped.add(dat[i])
        temp_set = []
        temp_set.append(dat[i])
        for j in range(i+1,len(dat)):
            
            if(dat[j] not in grouped):
                sim = np.sum(np.logical_and(data[i],data[j]))/np.sum(np.logical_or(data[i],data[j]))
                
                if(sim > sim_thresh):
                    #print("jhi")
                    temp_set.append(dat[j])
                    grouped.add(dat[j])
        groups.append(temp_set)
            

0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000


In [17]:
tot = 0
for i in groups:
    tot = tot+ len(i) 
    
print(tot)

19596


In [18]:
finalgenes = []
for group in groups:
    if(len(group) > n_thresh):
        counts = []
        for index in group:
            counts.append(data_sum[index])
        double_sorted = [x for _,x in sorted(zip(counts,group),reverse=True)]
        print(double_sorted[:5])
        print(data_sum[double_sorted[2]])
        finalgenes.extend(double_sorted[:5])

[17994, 17445, 12549, 6099, 18312]
1338
[10504, 14640, 16428, 9398, 12213]
1392
[3986, 3984, 14639, 6100, 5879]
978
[5864, 2486, 13129, 17383, 19084]
565
[5865, 18254, 14849, 10284, 10573]
601
[10505, 9047, 4376, 1679, 12601]
583
[16068, 7456, 12274, 14081, 4886]
665
[4900, 13539, 33, 3725, 8031]
523
[14675, 12600, 15124, 18379, 1384]
382
[1453, 13186, 19492, 4961, 13484]
545
[9394, 3879, 2648, 8540, 15391]
246
[7004, 8719, 4573, 15848, 15536]
322
[18175, 11379, 12267, 18869, 18908]
167
[18815, 3888, 8413, 9911, 9655]
524
[3709, 13487, 1545, 3697, 1308]
582
[16397, 9484, 14800, 3732, 15987]
551
[6228, 2492, 15851, 15066, 9608]
309
[19507, 12165, 4371, 2649, 10737]
237
[12137, 16750, 14068, 15680, 12336]
258
[10691, 384, 13561, 6991, 16341]
351
[14790, 4471, 8727, 7780, 2032]
139
[10552, 5880, 16510, 7269, 10566]
543
[10575, 9799, 6992, 6044, 10545]
275
[7741, 10106, 12141, 15538, 14742]
505
[1352, 17499, 3392, 303, 10397]
169
[16765, 1546, 6232, 11067, 15052]
92
[1303, 5313, 17403, 132

In [19]:
print(finalgenes) #indices of all genes

[17994, 17445, 12549, 6099, 18312, 10504, 14640, 16428, 9398, 12213, 3986, 3984, 14639, 6100, 5879, 5864, 2486, 13129, 17383, 19084, 5865, 18254, 14849, 10284, 10573, 10505, 9047, 4376, 1679, 12601, 16068, 7456, 12274, 14081, 4886, 4900, 13539, 33, 3725, 8031, 14675, 12600, 15124, 18379, 1384, 1453, 13186, 19492, 4961, 13484, 9394, 3879, 2648, 8540, 15391, 7004, 8719, 4573, 15848, 15536, 18175, 11379, 12267, 18869, 18908, 18815, 3888, 8413, 9911, 9655, 3709, 13487, 1545, 3697, 1308, 16397, 9484, 14800, 3732, 15987, 6228, 2492, 15851, 15066, 9608, 19507, 12165, 4371, 2649, 10737, 12137, 16750, 14068, 15680, 12336, 10691, 384, 13561, 6991, 16341, 14790, 4471, 8727, 7780, 2032, 10552, 5880, 16510, 7269, 10566, 10575, 9799, 6992, 6044, 10545, 7741, 10106, 12141, 15538, 14742, 1352, 17499, 3392, 303, 10397, 16765, 1546, 6232, 11067, 15052, 1303, 5313, 17403, 13244, 16442, 420, 3878, 12896, 14851, 11861, 800, 16489, 5364, 15397, 5665, 12332, 1442, 11040, 17404, 11424, 16088, 12671, 12473, 19

***ISR (indexed sparsity reduction): Miles***

In [45]:
def isr(genes_samples, genes_filter, n_isr, cgf):
    #filter the data set to only include the "important" genes (gene_filter) if cfg is True.
    if cgf:
        genes_samples = genes_samples[finalgenes]
    
    genes_samples_isr = []
    #transpose genes_samples so it is now samples as rows and genes as columns.
    genes_samples = genes_samples.T
    for i in range(len(genes_samples)):
        sample_row = genes_samples[i]
        n_nz = np.count_nonzero(sample_row)
        top_nonzero_cgf_idx = []
        j = 0
        while len(top_nonzero_cgf_idx) < n_isr:
            if j >= len(genes_filter):
                break
            if sample_row[genes_filter[j]] != 0:
                top_nonzero_cgf_idx.append(genes_filter[j])
            j += 1
        if n_nz < n_isr:
            while len(top_nonzero_cgf_idx) < n_isr:
                top_nonzero_cgf_idx.append(0)
        genes_samples_isr.append(top_nonzero_cgf_idx)
    print(genes_samples_isr)
    return genes_samples_isr
'''
genes_samples <- matrix of the gene sample data where the genes are the rows and samples are columns. 
samples_filter <- list of samples from CFG that should be kept.
n_isr <- threshhold parameter
cgf <- if True, then isr function will return the combined result of cgf and isr. Otherwise, it only returns 
       the results of isr. 
Returns a matrix with each row being a gene and the row is the list of that gene's most important samples.
'''
result = isr(data, finalgenes, n_isr=100, cgf=False)

[[17445, 5864, 10505, 16489, 8614, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [17445, 12549, 6044, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [12549, 14640, 5864, 384, 3575, 9405, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [17994, 17445, 5865, 4900, 11424, 12653, 8585

In [51]:
#save isr results only
with open('/home/mlee276/Desktop/TCGA-ML-main/deepgene_isr.pkl', 'wb') as f:
    pickle.dump([result,labels], f)

In [50]:
#save cfg + isr results.
